infra: Add dockerfile
voyage-plus-1010/v-taxi pull request #22
Opened 2023-09-19 13:50 UTC by XPECTER

# 변경 사항
dockerfile을 추가했습니다.

# 변경 이유
docker image를 빌드하기 위한 파일입니다.

---

- Close #5

2023-09-19 13:50 UTC, XPECTER commented
제가 놓친 옵션이 있는지 리뷰 부탁드립니다.

2023-09-19 13:55 UTC, kimseungbin commented
실행이 되나요?

2023-09-19 14:01 UTC, XPECTER commented
빌드는 되는데 실행이 안되네요. 해결하겠습니다.

2023-09-19 14:40 UTC, XPECTER commented
SWC를 이용한 빌드 및 작동까지 확인했습니다.

2023-09-19 15:00 UTC, kimseungbin requested changes
원래 이 코드의 가장 큰 문제점은 컨테이너 이미지로 '소스코드를 복사하지 않은 것' 이었습니다.
그 부분이 02ef9bbe42781908f16af4f0527fe8440e716db2 커밋 9번 줄에서 수정되었는데 다음과 같은 부분이 아쉬웠습니다.

1. 9번 줄과 나머지 변경사항은 이어지는 내용이지만 직접적으로 같이 커밋돼야할만큼 의존성이 큰 변경사항은 아닙니다. 또한, 해당 오류의 수정이라면 원래 카테고리였던 `infra` 나 문제를 해결한 `fix` 키워드가 더 적절했다고 생각합니다, 왜냐하면 제목 그대로 'chore: modified dockerfile' 라는 제목의 커밋인 경우 나중에 찾아볼 때 이것이 문제가 있어서 해결한 커밋인지 알아보기가 어려울 것이기 때문입니다. 다음으로 해당 내용을 인지하시고 고치셨을 때 커밋 제목만이 아닌 내용에도 어떤 부분을 놓쳐서 수정했는지 포함했으면 더 좋았을 것같습니다.

    예를들어서

    infra(Docker): fix missing COPY command

    Dockerfile 에서 소스코드를 복사하지 않던 문제를 COPY 명령으로 모든 파일을 복사하여 해결

2. `COPY . .` 자체의 문제점

    production 환경에서 repository 의 모든 내용을 이미지가 담고있을 필요는 없습니다. 예를들어 크게는 `/node_modules` 나 `/test`, 작게는 prettier 설정이나, `.gitignore` 등은 이미지 빌드하는 데는 아무런 역할을 하지 않는 파일들입니다. 이러한 파일들의 추가로 인해 빌드 시간과 이미지 용량이 늘어나는 문제가 발생합니다. 이 부분은 병합 전 새로 이슈를 작성하셔서 `.dockerignore` 로 해결하던지, `/src` 및 기타 필수 요소만 복사해서 이미지를 만드시는 것을 권해드립니다.

    또한 이와 연관되어 Node 에서 production 환경에서 `npm install` 명령어를 사용하지 않습니다. `npm ci` 를 이용해주세요.

    만약, 해당 Dockerfile 이 development 환경에서만 사용될걸 염두에 두시고 작성하셨다면, Dockerfile 에 development 임을 명시하고 production 용 파일이 하나 더 필요했을 것입니다.

---

다음으로 명령어 자체의 문제입니다.
`npm run build` 와 `npm start` 스크립트를 수정하지 않고 바로 사용한다면, `swc` 를 사용하지 않는 것처럼 보이게 됩니다. 이를 커밋 메세지에 자세한 설명을 추가하셨으면 좋겠습니다.

---

마지막으로 EXPOSE 3000 의 하드코딩 문제입니다. 해당 포트 번호는 local 이나 development 환경에서만 사용될 것이기 때문에 production 에 대비하는 443이나 80 포트에 대한 대비가 있었어야합니다. #4 에서 이미 환경변수에 관한 질문이 나왔는데, 이러한 부분들을 하드코딩하기보다는 담당자에게 전달할 필요가 있어보입니다.

2023-09-20 13:22 UTC, kimseungbin approved these changes

2023-09-20 14:37 UTC, gong-yeongbin approved these changes

2023-09-20 14:42 UTC, merged